### ISSUE TITLE
[to-do]  add targeted contributor-friendly documentation

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat.Flutter.SDK#4]
We need to add documentation, in a manner consistent across the entire monorepo,  for our targeted segment of contributors.  This will help to grow the community of contributors to the SDK project.

Making it easy to onboard and get contributing should be priority one (for all contributors with enough required skill - our target).

**Comment by yatendra2001** [comment]
@Sing-Li, I have created a pull request that adds the README and CONTRIBUTING files to the project. The README file provides an overview of the SDK, its features, and basic setup instructions. The CONTRIBUTING file contains guidelines for contributors and instructions on how to set up the development environment.

With these files in place, I believe it will be easier for new contributors to get started with the project and understand how they can contribute effectively. Please review the pull request and let me know if any changes are needed to make the onboarding process as smooth as possible for potential contributors.

**Comment by Sing-Li** [comment]
Thanks again @yatendra2001     I will comment inline there on the PR.

**Comment by yatendra2001** [comment]
@Sing-Li I think we can close this issue now. Merged PR: #5

**Comment by Sing-Li** [comment]
Thanks.
